# https://taskfile.dev

version: '3'


tasks:
  clean:
    cmds:
      - find rply -name "*.c" -delete
      - find rply -name "*.so" -delete
  cy-build:
    cmds:
      - cythonize -i rply
  profile:
    cmds:
      # you can inspect the output in qcachegrind or kcachegrind
      - yappi -f callgrind -o results/profile-rply.callgrind profile_rply.py
  grind:
    cmds:
      - qcachegrind results/profile-rply.callgrind
  type:
    cmds:
      - mypy rply --strict
    sources:
      - rply/*.py
  format:
    cmds:
      - find rply -name "*.py" -exec pyupgrade --py38-plus -- "{}" \;
      - find rply -name "*.py" -exec autoflake --in-place --remove-unused-variables -- "{}" \;
      - isort rply --profile=black
      - black --target-version=py38 rply
  annotate:
    cmds:
      - pytest --monkeytype-output ./monkeytype.sqlite3
      - monkeytype list-modules | grep rply. | xargs -I _ monkeytype apply --limit 5000 _
      - task: format